metadata <- read.csv('metadata.csv')
predacc9 <- read.csv('single_genome_results_10k_LSTM_O647Aaic_genomes.csv')
predacc4 <- read.csv('single_genome_results_5k.csv')
acc9withcds <- read.csv('single_genome_results_10k_LSTM_O647Aaic_CDS.csv')
predacc9 <- merge(predacc9, acc9withcds[c("genome", "f1_cds_1")], by="genome")
